name: JetBrains Build Only

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: extensions/intellij

jobs:
  build:
    runs-on: macos-latest
    steps:
      # 拉取源码
      - name: Fetch Sources
        uses: actions/checkout@v6

      # 验证 Gradle wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v6

      # 设置 Java 环境
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      # 设置 Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-home-cache-cleanup: true

      # 构建插件
      - name: Build Plugin
        run: ./gradlew buildPlugin --info --stacktrace

      # 准备插件 zip
      - name: Prepare Plugin Artifact
        id: artifact
        run: |
          cd build/distributions
          ls
          FILENAME=$(ls continue-intellij-extension-*.zip | head -1)
          echo "filename=${FILENAME%.????}" >> $GITHUB_OUTPUT

      # 上传插件 zip
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.artifact.outputs.filename }}
          path: ./extensions/intellij/build/distributions/*.zip
